services:
  rails:
    build:
      context: .
    container_name: association_rails
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/rails
    depends_on:
      - redis
      - sidekiq

  sidekiq:
    build:
      context: .
    container_name: association_sidekiq
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: bitnami/redis:7.2
    container_name: association_redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  redis_data:
