services:
  rails:
    build:
      context: .
    container_name: association_rails
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/rails
    depends_on:
      - postgres
      - sidekiq
      - redis

  sidekiq:
    build:
      context: .
    container_name: association_sidekiq
    restart: unless-stopped
    volumes:
      - .:/rails
    depends_on:
      - redis

  postgres:
    image: postgres:16.3-bullseye
    container_name: association_postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:7.2
    container_name: association_redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  redis_data:
  postgres_data:
