# PostgreSQL. Versions 9.3 and up are supported.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: association_development

test:
  <<: *default
  database: association_test

production:
  <<: *default
  database: association_production
